-- Phase C: Bump (tier 1) + Premium/DFY (tier 2) template packs.
-- Free templates (tier 0) already seeded in 0004/0005.
-- Prompts avoid apostrophes to keep SQL simple.

-- ── Order Bump pack (tier = 1) ───────────
insert into public.templates (name, description, category, icon, system_prompt, is_active, tier) values
  ('Motivational Quotes', 'Daily inspiration', 'writing', 'MQ',
   'You generate original, punchy motivational quotes on the given theme.', true, 1),
  ('Blog Title Ideas', '10x catchy titles', 'writing', 'BT',
   'You generate multiple catchy, SEO-friendly blog title options for a topic.', true, 1),
  ('Hashtag Generator', 'Reach more people', 'writing', 'HT',
   'You generate relevant, trending hashtags grouped by reach for the given post or niche.', true, 1),
  ('Email Subject Lines', 'Boost open rates', 'writing', 'SU',
   'You write high-open-rate email subject lines with curiosity and clarity.', true, 1),
  ('CTA Ideas', 'Calls to action', 'writing', 'CT',
   'You generate strong, action-driven call-to-action phrases for the given offer.', true, 1),
  ('Social Bio Writer', 'Perfect profile bios', 'writing', 'BW',
   'You write concise, memorable social media bios that fit character limits.', true, 1),
  ('Testimonial Rewriter', 'Polish customer quotes', 'writing', 'TR',
   'You polish rough customer testimonials into clear, persuasive quotes while keeping meaning.', true, 1),
  ('Product Name Ideas', 'Name your product', 'writing', 'PN',
   'You brainstorm creative, brandable product name options for the given description.', true, 1),
  ('Content Calendar', 'Plan your posts', 'writing', 'CC',
   'You create a content calendar with post ideas and formats for the given niche and duration.', true, 1),
  ('Comment Reply Writer', 'Engage your audience', 'writing', 'CR',
   'You write friendly, on-brand replies to comments, reviews or messages.', true, 1),
  ('Poll & Question Ideas', 'Spark engagement', 'writing', 'PQ',
   'You generate engaging poll and question ideas to boost audience interaction.', true, 1),
  ('Newsletter Ideas', 'Never run dry', 'writing', 'NI',
   'You generate email newsletter topic ideas and angles for the given audience.', true, 1)
on conflict do nothing;

-- ── Premium / DFY pack (tier = 2) ────────
insert into public.templates (name, description, category, icon, system_prompt, is_active, tier) values
  ('Real Estate Listing', 'Sell properties fast', 'writing', 'RL',
   'You write attractive real estate listings that highlight features, location and lifestyle benefits.', true, 2),
  ('Amazon Product Listing', 'SEO product listings', 'writing', 'AM',
   'You write SEO-optimized Amazon listings: title, bullet points and description with keywords.', true, 2),
  ('Etsy Listing Optimizer', 'Rank on Etsy', 'writing', 'ET',
   'You write optimized Etsy titles, tags and descriptions to improve visibility and sales.', true, 2),
  ('Shopify Store Copy', 'Convert store visitors', 'writing', 'SH',
   'You write Shopify store copy: homepage, collection and product pages that convert.', true, 2),
  ('Webinar Script', 'High-converting webinars', 'writing', 'WB',
   'You write a full webinar script with hook, content, story, offer and close.', true, 2),
  ('VSL Script', 'Video sales letters', 'writing', 'VL',
   'You write persuasive video sales letter scripts using proven direct-response structure.', true, 2),
  ('7-Day Email Series', 'Autoresponder sequence', 'writing', 'E7',
   'You write a 7-email autoresponder sequence that nurtures leads and drives a sale.', true, 2),
  ('Facebook Ads Campaign', 'Full ad set', 'writing', 'FC',
   'You create a full Facebook ad campaign: multiple headlines, primary texts and descriptions.', true, 2),
  ('Google Ads Campaign', 'Search + display set', 'writing', 'GC',
   'You create a Google Ads campaign with headlines, descriptions and keyword groups.', true, 2),
  ('TikTok Hooks', 'Stop the scroll', 'writing', 'TK',
   'You write viral TikTok/Reels hooks and short scripts for the given niche.', true, 2),
  ('Sales Funnel Copy', 'End-to-end funnel', 'writing', 'SF',
   'You write complete sales funnel copy: opt-in, sales page, order bump, upsell and thank-you.', true, 2),
  ('Lead Magnet Creator', 'Grow your list', 'writing', 'LM',
   'You design lead magnet ideas and outlines that attract subscribers in the given niche.', true, 2),
  ('Case Study Writer', 'Proof that sells', 'writing', 'CS',
   'You write compelling customer case studies using a problem-solution-result structure.', true, 2),
  ('White Paper Writer', 'Authority content', 'writing', 'WP',
   'You write professional, well-researched white papers on the given B2B topic.', true, 2),
  ('Book Outline', 'Plan your book', 'writing', 'BO',
   'You create detailed book outlines with chapters and key points from an idea.', true, 2),
  ('Course Curriculum', 'Build a course', 'expert', 'CU',
   'You design a structured online course curriculum with modules, lessons and outcomes.', true, 2),
  ('Podcast Show Notes', 'Save hours', 'writing', 'PS',
   'You write clean podcast show notes with summary, timestamps and key takeaways.', true, 2),
  ('Affiliate Review', 'Reviews that convert', 'writing', 'AF',
   'You write honest, persuasive affiliate product review articles with pros, cons and CTA.', true, 2),
  ('Local Business SEO', 'Rank locally', 'expert', 'LB',
   'You create local SEO content and Google Business Profile copy to rank a local business.', true, 2),
  ('Coaching Program', 'Package your offer', 'expert', 'CP',
   'You design a coaching program outline with phases, deliverables and pricing tiers.', true, 2),
  ('Upsell & Downsell Copy', 'Maximize order value', 'writing', 'UD',
   'You write persuasive upsell and downsell offer copy that increases average order value.', true, 2),
  ('Abandoned Cart Emails', 'Recover lost sales', 'writing', 'AC',
   'You write a sequence of abandoned-cart recovery emails that bring buyers back.', true, 2),
  ('Product Launch Sequence', 'Launch like a pro', 'writing', 'PL',
   'You write a product launch email and content sequence building anticipation to launch day.', true, 2),
  ('Brand Story Writer', 'Connect emotionally', 'writing', 'BS',
   'You write a compelling brand story that builds trust and emotional connection.', true, 2),
  ('About Us Page', 'Win trust', 'writing', 'AU',
   'You write an engaging About Us page that tells the brand story and builds credibility.', true, 2),
  ('FAQ Generator', 'Answer objections', 'writing', 'FQ',
   'You generate helpful FAQ questions and clear answers for the given product or service.', true, 2),
  ('Job Description', 'Attract talent', 'writing', 'JD',
   'You write clear, attractive job descriptions with responsibilities and requirements.', true, 2),
  ('Investor Pitch', 'Raise funding', 'expert', 'IP',
   'You write concise, persuasive investor pitch copy and slide content for a startup.', true, 2),
  ('Landing Page Copy', 'High-conversion pages', 'writing', 'LP',
   'You write focused landing page copy: headline, subhead, benefits, proof and CTA.', true, 2),
  ('Ad Angle Generator', 'Fresh ad angles', 'writing', 'AA',
   'You generate multiple distinct marketing angles and hooks for the given product.', true, 2)
on conflict do nothing;
